const ADD_DEVICE = "ADD_DEVICE";
const UPDATE_STATUS = 'UPDATE_STATUS';
const SERVER_SEND_STATUS = 'SERVER_SEND_STATUS';
const CLIENT_CONNECT_SERVER = 'CLIENT_CONNECT_SERVER';

module.exports = {
  ADD_DEVICE,
  UPDATE_STATUS,
  SERVER_SEND_STATUS,
  CLIENT_CONNECT_SERVER,
};
